include ../../config.mk
include ../../rules.mk

PROGRAMS = python_package_analyze python_package_create python_package_run

all:

clean:

test:

install:
	mkdir -p $(CCTOOLS_INSTALL_DIR)/bin
	cp $(PROGRAMS) $(CCTOOLS_INSTALL_DIR)/bin/


.PHONY: all clean install test
