# Configuration file for generating documentation via readthedocs.

# Required
version: 2

formats: all

mkdocs:
    configuration: mkdocs.yml

build:
    os: "ubuntu-20.04"
    tools:
      python: "3.9"
    jobs:
      pre_build:
        - cd doc && git clone https://github.com/jothepro/doxygen-awesome-css.git --branch v2.1.0
        - cp doc/cctools.doxygen.config doc/cctools.doxygen-mod.config
        - echo "HTML_EXTRA_STYLESHEET = doxygen-awesome-css/doxygen-awesome.css" >> doc/cctools.doxygen-mod.config
        - cd doc && doxygen cctools.doxygen-mod.config

# Additional pip modules needed from doc/requirements.txt
python:
    install:
    - requirements: doc/requirements.txt
