# Configuration file for generating documentation via readthedocs.

# Required
version: 2

formats: all

mkdocs:
    configuration: mkdocs.yml

build:
    os: ubuntu-20.04
    tools:
      python: 3.7
    jobs:
      pre_build:
        - cd docs && doxygen cctools.doxygen.config

# Additional pip modules needed from doc/requirements.txt
python:
    version: 3.7
    install:
    - requirements: doc/requirements.txt
