#!/bin/sh

show_help() 
{
	echo "Use: condor_submit_workers [options] <servername> <port> <num-workers>"
	echo "options:"
	echo "  -N <name> Preferred master name."
	echo "  -S        Run as a shared worker."
	echo "  -t <time> Abort after this amount of idle time. (default=900s)"
	echo "  -h        Show this help message."
	exit 1
}

arguments=""
use_auto=0

while getopts aSN:t:h opt 
do
	case "$opt" in
		S)  arguments="$arguments -S"; use_auto=1;;
		N)  arguments="$arguments -N $OPTARG"; use_auto=1;;
		t)  arguments="$arguments -t $OPTARG";;
		h)  show_help;;
		\?) show_help;;
	esac
done

shift $(expr $OPTIND - 1)

if [ $use_auto = 0 ]; then
    if [ X$3 = X ]
    then
	show_help	
    fi
    host=$1
    port=$2
    count=$3
else
    if [ X$1 = X ]
    then
	show_help	
    fi
    host=
    port=
    count=$1
fi

worker=`which worker 2>/dev/null`
if [ $? != 0 ]
then
	echo "$0: please add 'worker' to your PATH."
	exit 1
fi

mkdir /tmp/${USER}-workers
cd /tmp/${USER}-workers
cp $worker .

condor_submit << EOF
universe = vanilla
executable = worker
arguments = $arguments $host $port
transfer_input_files = worker
should_transfer_files = yes
when_to_transfer_output = on_exit
output = worker.\$(PROCESS).output
error = worker.\$(PROCESS).error
log = workers.log
getenv = true
queue $count
EOF

exit $?
