#!/bin/sh

if [ X$3 = X ]
then
	echo "use: worker <servername> <port> <num-workers>"
	exit 1
fi

worker=`which worker`
if [ $? != 0 ]
then
	echo "$0: please add 'worker' to your PATH."
	exit 1
fi

host=$1
port=$2
count=$3

condor_submit << EOF
universe = vanilla
executable = $worker
arguments = $host $port
should_transfer_files = yes
when_to_transfer_output = on_exit
log = /tmp/${USER}-workers.log
queue $count
EOF

exit $?
