#!/bin/sh

if [ X$3 = X ]
then
	echo "use: condor_submit_workers <servername> <port> <num-workers>"
	exit 1
fi

worker=`which worker`
if [ $? != 0 ]
then
	echo "$0: please add 'worker' to your PATH."
	exit 1
fi

mkdir /tmp/${USER}-workers
cd /tmp/${USER}-workers
cp $worker .

host=$1
port=$2
count=$3

condor_submit << EOF
universe = vanilla
executable = worker
arguments = $host $port
transfer_input_files = worker
should_transfer_files = yes
when_to_transfer_output = on_exit
output = worker.\$(PROCESS).output
error = worker.\$(PROCESS).error
log = workers.log
getenv = true
queue $count
EOF

exit $?
