{% set version = "7.0.15" %}

package:
  name: cctools
  version: {{version}}

source:
  url: http://ccl.cse.nd.edu/software/files/cctools-{{ version }}-source.tar.gz

build:
  rpaths:
    - /lib

requirements:
  build:
    - python
    - swig
  run:
    - python

test:
  import:
    - work_queue
  commands:
    - resource_monitor -h
    - makeflow -h

about:
  home: http://ccl.cse.nd.edu
  license: GNU GPL version 2
  summary: The Cooperative Computing Tools contains Chirp, Makeflow, JX, and Work Queue.
