# Note to cctools maintainers:
# When updating cctools versions, only the version and src_checksum variables
# should be modified.
# Get the checksum of the cctools-VERSION-source.tar.gz tarball as:
# openssl sha256  cctools-VERSION-source.tar.gz
# Note we use the name "ndcctools" as there is already another project in
# anaconda called cctools.

{% set name = "ndcctools" %}
{% set version = "7.0.20" %}
{% set src_checksum = "387c9ca8a2d8700fcb77a688c4f769bbd1cad7d2c070205b024593d7a27a193a" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: http://ccl.cse.nd.edu/software/files/cctools-{{ version }}-source.tar.gz
  sha256: {{ src_checksum }}

build:
  number: 3
  skip: True  # [win]
  skip: True  # [osx and py==27]
  rpaths:
    - lib/

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - swig
    - make
  host:
    - python
    - perl  # [linux]
    - zlib
  run:
    - python
    - perl  # [linux]
    - zlib

test:
  imports:
    - work_queue
  commands:
    - makeflow -h
    - work_queue_worker -h
    - work_queue_factory -h

about:
  home: http://ccl.cse.nd.edu/
  license: GPL-2.0
  license_file: COPYING
  summary: 'The Cooperative Computing Tools contains Chirp, Makeflow, JX, and Work Queue.'
  description: |
    The Cooperative Computing Tools (cctools) are a collection of programs that
    enable large scale distributed computing on systems such as clusters,
    clouds, and grids. These tools are commonly used in fields of science and
    engineering that rely on large amounts of computing.
  doc_url: https://cctools.readthedocs.io
  dev_url: https://github.com/cooperative-computing-lab/cctools

extra:
  recipe-maintainers:
    - btovar
    - dthain
