include ../../../../../config.mk

.PHONY: all install lint format test clean

all:

install: all

lint:

format:

test:
	cd $(CURDIR) && $(CCTOOLS_PYTHON3) task_group_parity.py

clean:
	rm -rf __pycache__
