#! /usr/bin/env python

# Copyright (C) 2011- The University of Notre Dame
# This software is distributed under the GNU General Public License.
# See the file COPYING for details.
#
# This simple script splits a fasta file into pieces
#

import sys, re

if(len(sys.argv) < 3) :
	sys.stderr.write("Usage: split_fasta.py query_granularity fasta_file")
	sys.exit(1)
num_seq = sys.argv[1]
query = sys.argv[2]
num_chars = 0
num_queries = 0
num_jobs = 0

FILE  = open(query, "r")
OF = open(query + "." + str(num_jobs), "w")
for line in FILE:
	if(re.search('^>', line)):
		if( num_queries > (int(num_seq) - 1) ):
			OF.close()
			num_jobs = num_jobs + 1
			num_queries = 0
			OF = open(query + "." + str(num_jobs), "w")
			OF.write(line)
		else :
			OF.write(line)
		num_queries += 1
	else :
		OF.write(line)
FILE.close()
OF.close()
sys.exit(0)
