# This file was automatically generated by SWIG (https://www.swig.org).
# Version 4.4.1
#
# Do not make changes to this file unless you know what you are doing - modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
# Import the low-level C/C++ module
if getattr(globals().get("__spec__"), "parent", None) or __package__ or "." in __name__:
    from . import _vine_graph_capi
else:
    import _vine_graph_capi

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "this":
            set(self, name, value)
        elif name == "thisown":
            self.this.own(value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


import cvine
class vine_graph(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    nodes = property(_vine_graph_capi.vine_graph_nodes_get, _vine_graph_capi.vine_graph_nodes_set)
    super_leader_to_members = property(_vine_graph_capi.vine_graph_super_leader_to_members_get, _vine_graph_capi.vine_graph_super_leader_to_members_set)
    outfile_cachename_to_node = property(_vine_graph_capi.vine_graph_outfile_cachename_to_node_get, _vine_graph_capi.vine_graph_outfile_cachename_to_node_set)
    inout_filename_to_cached_name = property(_vine_graph_capi.vine_graph_inout_filename_to_cached_name_get, _vine_graph_capi.vine_graph_inout_filename_to_cached_name_set)
    supernode_leader_child_to_input_source = property(_vine_graph_capi.vine_graph_supernode_leader_child_to_input_source_get, _vine_graph_capi.vine_graph_supernode_leader_child_to_input_source_set)
    checkpoint_dir = property(_vine_graph_capi.vine_graph_checkpoint_dir_get, _vine_graph_capi.vine_graph_checkpoint_dir_set)
    output_dir = property(_vine_graph_capi.vine_graph_output_dir_get, _vine_graph_capi.vine_graph_output_dir_set)
    task_runner_library_name = property(_vine_graph_capi.vine_graph_task_runner_library_name_get, _vine_graph_capi.vine_graph_task_runner_library_name_set)
    task_runner_function_name = property(_vine_graph_capi.vine_graph_task_runner_function_name_get, _vine_graph_capi.vine_graph_task_runner_function_name_set)
    checkpoint_fraction = property(_vine_graph_capi.vine_graph_checkpoint_fraction_get, _vine_graph_capi.vine_graph_checkpoint_fraction_set)
    prune_depth = property(_vine_graph_capi.vine_graph_prune_depth_get, _vine_graph_capi.vine_graph_prune_depth_set)
    print_graph_details = property(_vine_graph_capi.vine_graph_print_graph_details_get, _vine_graph_capi.vine_graph_print_graph_details_set)
    chain_grouping_enabled = property(_vine_graph_capi.vine_graph_chain_grouping_enabled_get, _vine_graph_capi.vine_graph_chain_grouping_enabled_set)

    def __init__(self):
        _vine_graph_capi.vine_graph_swiginit(self, _vine_graph_capi.new_vine_graph())
    __swig_destroy__ = _vine_graph_capi.delete_vine_graph

# Register vine_graph in _vine_graph_capi:
_vine_graph_capi.vine_graph_swigregister(vine_graph)

def vine_graph_input_producer_node(g, parent, child):
    return _vine_graph_capi.vine_graph_input_producer_node(g, parent, child)

def vine_graph_create(runtime_dir):
    return _vine_graph_capi.vine_graph_create(runtime_dir)

def vine_graph_add_node(g):
    return _vine_graph_capi.vine_graph_add_node(g)

def vine_graph_set_target(g, node_id):
    return _vine_graph_capi.vine_graph_set_target(g, node_id)

def vine_graph_add_dependency(g, parent_id, child_id):
    return _vine_graph_capi.vine_graph_add_dependency(g, parent_id, child_id)

def vine_graph_finalize(g):
    return _vine_graph_capi.vine_graph_finalize(g)

def vine_graph_get_node_heavy_score(g, node_id):
    return _vine_graph_capi.vine_graph_get_node_heavy_score(g, node_id)

def vine_graph_get_node_outfile_remote_name(g, node_id):
    return _vine_graph_capi.vine_graph_get_node_outfile_remote_name(g, node_id)

def vine_graph_delete(g):
    return _vine_graph_capi.vine_graph_delete(g)

def vine_graph_get_task_runner_library_name(g):
    return _vine_graph_capi.vine_graph_get_task_runner_library_name(g)

def vine_graph_set_task_runner_function_name(g, task_runner_function_name):
    return _vine_graph_capi.vine_graph_set_task_runner_function_name(g, task_runner_function_name)

def vine_graph_tune(g, name, value):
    return _vine_graph_capi.vine_graph_tune(g, name, value)

def vine_graph_node_is_supernode_leader(n):
    return _vine_graph_capi.vine_graph_node_is_supernode_leader(n)

def vine_graph_supernode_leader_node(g, n):
    return _vine_graph_capi.vine_graph_supernode_leader_node(g, n)

def vine_graph_group_chain_like_tasks(g):
    return _vine_graph_capi.vine_graph_group_chain_like_tasks(g)
TASK_PRIORITY_MODE_RANDOM = _vine_graph_capi.TASK_PRIORITY_MODE_RANDOM
TASK_PRIORITY_MODE_DEPTH_FIRST = _vine_graph_capi.TASK_PRIORITY_MODE_DEPTH_FIRST
TASK_PRIORITY_MODE_BREADTH_FIRST = _vine_graph_capi.TASK_PRIORITY_MODE_BREADTH_FIRST
TASK_PRIORITY_MODE_FIFO = _vine_graph_capi.TASK_PRIORITY_MODE_FIFO
TASK_PRIORITY_MODE_LIFO = _vine_graph_capi.TASK_PRIORITY_MODE_LIFO
TASK_PRIORITY_MODE_LARGEST_INPUT_FIRST = _vine_graph_capi.TASK_PRIORITY_MODE_LARGEST_INPUT_FIRST
TASK_PRIORITY_MODE_LARGEST_STORAGE_FOOTPRINT_FIRST = _vine_graph_capi.TASK_PRIORITY_MODE_LARGEST_STORAGE_FOOTPRINT_FIRST
class vine_graph_executor(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    graph = property(_vine_graph_capi.vine_graph_executor_graph_get, _vine_graph_capi.vine_graph_executor_graph_set)
    manager = property(_vine_graph_capi.vine_graph_executor_manager_get, _vine_graph_capi.vine_graph_executor_manager_set)
    task_id_to_node = property(_vine_graph_capi.vine_graph_executor_task_id_to_node_get, _vine_graph_capi.vine_graph_executor_task_id_to_node_set)
    resubmit_queue = property(_vine_graph_capi.vine_graph_executor_resubmit_queue_get, _vine_graph_capi.vine_graph_executor_resubmit_queue_set)
    time_first_task_dispatched = property(_vine_graph_capi.vine_graph_executor_time_first_task_dispatched_get, _vine_graph_capi.vine_graph_executor_time_first_task_dispatched_set)
    time_last_task_retrieved = property(_vine_graph_capi.vine_graph_executor_time_last_task_retrieved_get, _vine_graph_capi.vine_graph_executor_time_last_task_retrieved_set)
    makespan_us = property(_vine_graph_capi.vine_graph_executor_makespan_us_get, _vine_graph_capi.vine_graph_executor_makespan_us_set)
    time_spent_on_cut_propagation = property(_vine_graph_capi.vine_graph_executor_time_spent_on_cut_propagation_get, _vine_graph_capi.vine_graph_executor_time_spent_on_cut_propagation_set)
    completed_recovery_tasks = property(_vine_graph_capi.vine_graph_executor_completed_recovery_tasks_get, _vine_graph_capi.vine_graph_executor_completed_recovery_tasks_set)
    pfs_usage_bytes = property(_vine_graph_capi.vine_graph_executor_pfs_usage_bytes_get, _vine_graph_capi.vine_graph_executor_pfs_usage_bytes_set)
    total_preprocessing_time_us = property(_vine_graph_capi.vine_graph_executor_total_preprocessing_time_us_get, _vine_graph_capi.vine_graph_executor_total_preprocessing_time_us_set)
    total_postprocessing_time_us = property(_vine_graph_capi.vine_graph_executor_total_postprocessing_time_us_get, _vine_graph_capi.vine_graph_executor_total_postprocessing_time_us_set)
    task_priority_mode = property(_vine_graph_capi.vine_graph_executor_task_priority_mode_get, _vine_graph_capi.vine_graph_executor_task_priority_mode_set)
    failure_injection_step_percent = property(_vine_graph_capi.vine_graph_executor_failure_injection_step_percent_get, _vine_graph_capi.vine_graph_executor_failure_injection_step_percent_set)
    progress_bar_update_interval_sec = property(_vine_graph_capi.vine_graph_executor_progress_bar_update_interval_sec_get, _vine_graph_capi.vine_graph_executor_progress_bar_update_interval_sec_set)

    def __init__(self):
        _vine_graph_capi.vine_graph_executor_swiginit(self, _vine_graph_capi.new_vine_graph_executor())
    __swig_destroy__ = _vine_graph_capi.delete_vine_graph_executor

# Register vine_graph_executor in _vine_graph_capi:
_vine_graph_capi.vine_graph_executor_swigregister(vine_graph_executor)

def vine_graph_executor_create(manager, graph):
    return _vine_graph_capi.vine_graph_executor_create(manager, graph)

def vine_graph_executor_create_graph(manager):
    return _vine_graph_capi.vine_graph_executor_create_graph(manager)

def vine_graph_executor_delete(e):
    return _vine_graph_capi.vine_graph_executor_delete(e)

def vine_graph_executor_add_node(e):
    return _vine_graph_capi.vine_graph_executor_add_node(e)

def vine_graph_executor_finalize(e):
    return _vine_graph_capi.vine_graph_executor_finalize(e)

def vine_graph_executor_add_task_input(e, task_id, filename):
    return _vine_graph_capi.vine_graph_executor_add_task_input(e, task_id, filename)

def vine_graph_executor_add_task_output(e, task_id, filename):
    return _vine_graph_capi.vine_graph_executor_add_task_output(e, task_id, filename)

def vine_graph_executor_tune(e, name, value):
    return _vine_graph_capi.vine_graph_executor_tune(e, name, value)

def vine_graph_executor_execute(e):
    return _vine_graph_capi.vine_graph_executor_execute(e)

def vine_graph_executor_get_makespan_us(e):
    return _vine_graph_capi.vine_graph_executor_get_makespan_us(e)

def vine_graph_executor_get_total_recovery_tasks(e):
    return _vine_graph_capi.vine_graph_executor_get_total_recovery_tasks(e)

def vine_graph_executor_get_completed_recovery_tasks(e):
    return _vine_graph_capi.vine_graph_executor_get_completed_recovery_tasks(e)

