#!/bin/bash

export GNUPLOT_DEFAULT_GDFONT=inconsolata

job=$(realpath "$1")
confuga=$(realpath "$2")

data=$(mktemp)

echo $0
sqlite3 -separator $'\t' > "$data"  <<EOF
ATTACH 'file://${job}?mode=ro' as Job;
ATTACH 'file://${confuga}?mode=ro' as Confuga;

SELECT TransferJob.id, TransferJob.time_commit, File.size/(MAX(TransferJob.time_complete-TransferJob.time_commit, 1))
	FROM Confuga.TransferJob JOIN Confuga.File ON TransferJob.fid = File.id
UNION ALL
SELECT TransferJob.id, TransferJob.time_complete+1 /* prevent time_commit == time_complete */, -File.size/(MAX(TransferJob.time_complete-TransferJob.time_commit, 1))
	FROM Confuga.TransferJob JOIN Confuga.File ON TransferJob.fid = File.id;
EOF
cat "$data"

gnuplot <<EOF
set terminal postscript eps mono
set output 'aggregate.eps'

set rmargin 4

set xdata time
set timefmt "%s"
set format x "%H:%M"
set xlabel "Time (Minutes)"
set xtics rotate by -45 offset -.8,0

set ylabel "Aggregate Transfer (Bytes/S)"
set format y "%0.1e"

first=0;
offset=0;
func(x)=(offset=(first==0)?x:offset,first=1,x-offset)


plot [][0:] "${data}" using (func(\$2)):3 title "Aggregate Transfer" smooth cumulative
EOF

# vim: set noexpandtab tabstop=4:
