#!/bin/bash

export GNUPLOT_DEFAULT_GDFONT=inconsolata

job=$(realpath "$1")
confuga=$(realpath "$2")

data=$(mktemp)

echo $0
sqlite3 -separator $'\t' > "$data"  <<EOF
ATTACH 'file://${job}?mode=ro' as Job;
ATTACH 'file://${confuga}?mode=ro' as Confuga;

SELECT UPPER(HEX(TransferJob.fid)), TransferJob.time_complete, File.size
	FROM Confuga.TransferJob JOIN Confuga.File ON TransferJob.fid = File.id
	ORDER BY TransferJob.time_complete;
EOF
cat "$data"

gnuplot <<EOF
set terminal postscript eps mono
set output 'cumulative.eps'

set xdata time
set timefmt "%s"
set format x "%H:%M"
set xlabel "Time (Minutes)"

set ylabel "Transferred (MB)"
set format y "%0.1e"

plot "${data}" using 2:(\$3/(2**20)) title "Cumulative Transfer" smooth cumulative
EOF

# vim: set noexpandtab tabstop=4:
