#!/bin/sh

if [ -z "$JAVA_HOME" ]
then
	echo 2>&1 "$0: Sorry, you must set JAVA_HOME to point to your Java installation."
	exit 1
fi

if [ -z "$HADOOP_HOME" ]
then
	echo 2>&1 "$0: Sorry, you must set HADOOP_HOME to point to your Hadoop installation."
	exit 1
fi

if [ -z "$CLASSPATH" ]; then
	CLASSPATH="${JAVA_HOME}/jdk/jre/lib:${HADOOP_HOME}/conf"
else
	CLASSPATH="${CLASSPATH}:${JAVA_HOME}/jdk/jre/lib:${HADOOP_HOME}/conf"
fi
for file in "${HADOOP_HOME}"/*.jar "${HADOOP_HOME}"/lib/*.jar; do
	CLASSPATH="${CLASSPATH}:$file"
done
export CLASSPATH

if [ -z "$LIBJVM_PATH" ]; then
	LIBJVM_PATH=$(find "${JAVA_HOME}/" -path libjvm.so)
	if [ -z "$LIBJVM_PATH" ]; then
		echo 2>&1 "$0: Sorry but could not find libjvm.so anywhere under JAVA_HOME=$JAVA_HOME"
		exit 1
	fi
	export LIBJVM_PATH
fi

if [ -z "$LIBHDFS_PATH" ]; then
	if [ `uname -m` = x86_64 ]; then
		LIBHDFS_PATH="$HADOOP_HOME/c++/`uname`-amd64-64/lib/libhdfs.so"
	else
		LIBHDFS_PATH="$HADOOP_HOME/c++/`uname`-i386-32/lib/libhdfs.so"
	fi
	if [ ! -e "$LIBHDFS_PATH" ]; then
		echo 2>&1 "$0: Sorry but could not find libhdfs.so anywhere under HADOOP_HOME=$HADOOP_HOME"
		exit 1
	fi
	export LIBHDFS_PATH
fi

exec "$(dirname $0)/chirp_server" "$@"

# vim: set noexpandtab tabstop=4:
