include ../../Makefile.config
include ../../Makefile.rules

all:

clean:
	rm -rf test_20.cfa test_20.cand.output test_20.sw.ovl test_20.banded.ovl test_20.cand repeats.meryl rect.bcand rect001.cfa rect005.cfa  sand_filter_mer_seq sand_sw_alignment sand_banded_alignment filter.log sw.log worker.log

test:
	./test_example.sh

install:
