CCTOOLS_HOME = ../..

include ${CCTOOLS_HOME}/Makefile.config
include ${CCTOOLS_HOME}/Makefile.rules

TARGETS=hogmem msqrt

all: ${TARGETS}

hogmem: hogmem.c 

msqrt: msqrt.c

test:

clean:
	-rm *.o ${TARGETS}

install:
