#!/bin/bash

source "$(dirname "$0")"/test-common.bash

DIR="$(basename "$0").workflow"

if ! [ -d "$DIR" ]; then
	[ -r "$0.py" ] || fatal "Cannot find weaver script: $0.py"
	weaver -N -O "$DIR" "$0.py"
fi

for pull in $(for exp in 36 30 35 34 33 32 31; do printf '%d\t' $((1+1*2**exp)); done) 0; do
	for scheduler in fifo-0; do
		for replication in push-async-1; do
			testrun "$DIR" "$(pwd)/test.$(printf '%016x' "${pull}").${scheduler}.${replication}" "scheduler=${scheduler}&replication=${replication}&pull-threshold=${pull}"
		done
	done
done

# vim: set noexpandtab tabstop=4:
