#! /usr/bin/env python

# Copyright (C) 2023- The University of Notre Dame
# This software is distributed under the GNU General Public License.
# See the file COPYING for details.

import sys
import matplotlib.pyplot as plt

def read_fields(f, lines_patience = 10):
    for line in f:
        if line[0] != '#':
            lines_patience = lines_patience - 1
        else:
            return line.strip('#\n\r\t ').split()
        if lines_patience < 1:
            break
    sys.stderr.write("Could not find fields. This is probably not a performance log...\n")
    sys.exit(1)

if __name__ == "__main__":
    f = open(sys.argv[1])

    fields = read_fields(f)
    timestamp_offset = fields.index("timestamp")
    sched_offset = fields.index("time_scheduling")
    dispatch_offset = fields.index("tasks_dispatched")

    sched_time_accum = []
    sched_time_diffs = []

    f.seek(0)

    last_dispatch = 0
    for line in f:
        if line[0] == "#":
            continue
        items = line.strip("\n\r\t ").split()
        dispatch = int(items[dispatch_offset])

        if dispatch > last_dispatch:
            last_dispatch = dispatch
            sched_time_accum.append(int(items[sched_offset]))
            if len(sched_time_accum) > 1:
                sched_time_diffs.append(int(items[sched_offset]) - sched_time_accum[-2])

    f1 = plt.subplot(1, 2, 1)
    plt.xlabel("Tasks Scheduled")
    plt.ylabel("Accumulated Time (us)")
    plt.plot(sched_time_accum)

    f2 = plt.subplot(1, 2, 2)
    plt.xlabel("Tasks Scheduled")
    plt.ylabel("Schedule Time (us)")
    plt.plot(sched_time_diffs)

    plt.show()






    
    


