#! /usr/bin/env python

# Copyright (C) 2025- The University of Notre Dame
# This software is distributed under the GNU General Public License.
# See the file COPYING for details.

# vine_plot_taskgraph converts the raw taskgraph format into an external form that can be plotted.
# The taskgraph written by the TaskVine manager comes in one of two formats:
#
# 1 - The old format was written directly out as an input file for the Graphviz DOT language. This was easy to use dot specifically, but a bit difficult to parse and use by other tools. If the input begins with "digraph g {" then this tool just turns around and calls the DOT program directly to generate a PDF.
#
# 2 - The new format is somewhat compressed and writes out exactly one line for each task and file:
#
# taskvine taskgraph version 2
# TASK taskid \"name\" INPUTS fileid1 fileid2 fileid3 ... OUTPUTS fileid4 fileid5 ...
# FILE fileid \"name\" size
#
# This format is easier to parse, and permits us to adjust the style of the graph
# post-runtime, and facilitates converting to other rendering formats in the future.

import os
import sys
import shlex
import shutil
import argparse

# Number of errors to tolerate on the input before giving up
max_error_count = 5

# Dictionary of tasks, key is taskid.
taskinfo = {}

# Dictionary of files, key is fileid.
fileinfo = {}

# Dict of tasks, key is category name.
categories = {}

# List of tasks in the order of "RUNNING" evennts in the txn log.
start_ordering = []

# Determine if taskgraph is in old format by looking for "digraph g {"
# which is the preamble for the graphviz dot format.

def taskgraph_is_old_format( filename ):
    with open(filename) as file:
        line = file.readline()
        if line.startswith("digraph"):
            return True
        else:
            return False
            

def parse_txn_file( filename ):
    txn = filename
    global taskinfo
    global categories
    global start_ordering

    with open(txn) as transactions:
        for line in transactions:
            fields = shlex.split(line)
            # if a task fails and retries on multiple workers we will end up with the one who succeeded.
            if len(fields) >= 3 and fields[4] == "RUNNING":
                workerid = fields[5]
                taskid = fields[3]
                taskinfo['T' + taskid]["worker"] = workerid
                start_ordering.append('T' + taskid)
            elif len(fields) >= 3 and fields[4] == "READY":
                taskid = fields[3]
                taskinfo['T' + taskid]["category"] = fields[5]
                categories[fields[5]] = categories.get(fields[5], []) + ['T' + taskid]

# Parse the taskgraph file and load all nodes/edges into the taskinfo and fileinfo dictionaries.
def parse_taskgraph_file( args, filename ):

    global taskinfo
    global fileinfo
    global max_error_count
    error_count = 0
        
    
    linenum = 0
    with open(filename) as file:
        for nline in file:
            line = nline.rstrip()
            linenum = linenum+1

            if line.startswith("#"):
                # skip over comments
                continue
            elif line.startswith("TASK"):
                # use shlex.split to respect quoted fields in the input
                fields = shlex.split(line)

                # TASK line starts with task properties
                taskid = fields[1]
                name = fields[2]

                # list of fileids following INPUT
                i = 4
                inputs = list()
                while fields[i] != "OUTPUTS":
                    inputs.append(fields[i])
                    i=i+1

                # list of fileids following OUTPUT
               	i=i+1 
                outputs = list()
                while i < len(fields):
                    outputs.append(fields[i])
                    i=i+1

                # record the complete task
                taskinfo[taskid] = { "name" : name, "inputs" : inputs, "outputs" : outputs }


            elif line.startswith("FILE"):
                # use shlex.split to respect quoted fields in the input
                (x,fileid,name,size) = shlex.split(line)
                fileinfo[fileid] = { "name" : name, "size" : size, "source": None, "sinks": list() }

            else:
                print("WARNING: invalid data at {}:{}: {}\n".format(filename,linenum,line))
                error_count = error_count + 1
                if(error_count > max_error_count):
                    print("aborting after {} errors".format(max_error_count))
                    sys.exit(1)
                


# Write the contents of the taskgraph back out as a graphviz dot file.
# Apply various styling parameters to control the output.
                    
def print_taskgraph_as_dot( args, filename ):

    global taskinfo
    global fileinfo
    
    with open(filename,"w") as fp:

        print("digraph g {",file=fp)


        if args.heatmap_ordering:
            num_tasks = len(start_ordering)
            color_sep = int(255/num_tasks)
            for i, taskid in enumerate(start_ordering):
                color_val = 255 - i*color_sep
                print("node [style=filled,font=Helvetica,fontsize={},shape=oval,color={}];".format(args.fontsize, f"\"#{color_val:02x}0000\""), file=fp)
                if args.labels:
                    label = taskinfo[taskid]["name"]
                else:
                    label = ""
                print("\"{}\" [label=\"{}\"];".format(taskid,label),file=fp)

        elif args.show_workers:
            # Give each worker its own color
             for taskid, t in taskinfo.items():
                worker_hexval = t["worker"].split('-')[-1]
                worker_hexval = bytes.fromhex(worker_hexval)
                # take the last 3 bytes of the workerid and use that as a hex color value for the node
                print("node [style=filled,font=Helvetica,fontsize={},shape=oval,color={}];".format(args.fontsize, f"\"#{worker_hexval.hex()[-6:]}\""), file=fp)
                if args.labels:
                    label = t["name"]
                else:
                    label = ""
                print("\"{}\" [label=\"{}\"];".format(taskid,label),file=fp)
        
        else:
            # Emit all of the tasks with a constant green style
            print("node [style=filled,font=Helvetica,fontsize={},shape=oval,color=green];".format(args.fontsize), file=fp)
            for t in taskinfo:
                if args.labels:
                    label = taskinfo[t]["name"]
                else:
                    label = ""
                print("\"{}\" [label=\"{}\"];".format(t,label),file=fp)

        # Emit all of the files with a constant style
        print("node [style=filled,font=Helvetica,fontsize={},shape=rect,color=blue];".format(args.fontsize), file=fp)
        for f in fileinfo:
            if args.labels:
                label = fileinfo[f]["name"]
            else:
                label = ""
            print("\"{}\" [label=\"{}\"];".format(f,label),file=fp)

        # Finally emit all of the edges.

        if args.cluster_categories:
            # express edges per category in a cluster
                for category, tasks in categories.items():
                    print("subgraph cluster_{} {{".format(category), file=fp)
                    for t in tasks:
                        for f in taskinfo[t]["inputs"]:
                            print("\"{}\" -> \"{}\";".format(f,t),file=fp);
                        for f in taskinfo[t]["outputs"]:
                            print("\"{}\" -> \"{}\";".format(t,f),file=fp);
                    print("}", file=fp)

        else:
            for t in taskinfo:
                for f in taskinfo[t]["inputs"]:
                    print("\"{}\" -> \"{}\";".format(f,t),file=fp);
                for f in taskinfo[t]["outputs"]:
                    print("\"{}\" -> \"{}\";".format(t,f),file=fp);

        print("}\n",file=fp)

        
if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        prog="vine_plot_taskgraph",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
        description="Plot TaskVine workflow structure from a taskgraph log file."
    )

    parser.add_argument("taskgraph", help="taskgraph log file")
    parser.add_argument("--output", nargs="?", required=True, help="output PDF file to create")
    parser.add_argument("--labels", action="store_true", help="display task/file labels")
    parser.add_argument("--fontsize",nargs="?", default=10 ,help="fontsize of task/file labels, in points")
    parser.add_argument("--add-txn", nargs="?", default=None, help="parse specified transactions log to enable additional options")
    parser.add_argument("--show-workers", action="store_true", help="task nodes are assigned a unique color based on the worker they were sent to. requires --add-txn.")
    parser.add_argument("--heatmap-ordering", action="store_true", help="task nodes are colored on a heatmap scale based on their observed scheduling order. requires --add-txn.")
    parser.add_argument("--cluster-categories", action="store_true", help="tasks are grouped into clusters based on their category. requires --add-txn.")

    args = parser.parse_args()

    print("reading taskgraph {}...".format(args.taskgraph))

    if taskgraph_is_old_format(args.taskgraph):
        print("taskgraph is in version 1 format")
        dotfile = args.taskgraph
    else:
        print("taskgraph is in version 2 format")
        parse_taskgraph_file( args, args.taskgraph )

        if args.add_txn:
            parse_txn_file(args.add_txn)

        dotfile = "{}.dot".format(args.taskgraph)
        
        print("writing dot graph {}...".format(dotfile))
        print_taskgraph_as_dot( args, dotfile )

    path_to_dot = shutil.which("dot")
    if path_to_dot:
        print("found graphviz dot at {}".format(path_to_dot))
    else:
        print("{}: could not find graphviz dot in PATH!")
        print("Please install graphviz before proceeding.")
        sys.exit(1)

    print("running dot to create {} (this may be slow)...".format(args.output))
    os.system("dot -Tpdf {} > {}".format(dotfile,args.output))
    
