include ../../Makefile.config
include ../../Makefile.rules

all:

clean:

test:

install:
	install -d ${CCTOOLS_INSTALL_DIR}/doc
	install install.html ${CCTOOLS_INSTALL_DIR}/doc
	install watchdog.html ${CCTOOLS_INSTALL_DIR}/doc

