#! /usr/bin/env python

import sys
import json
import jsonschema

if len(sys.argv) != 3:
    print("Usage: {} schema-file document-file".format(sys.argv[0]))

with open(sys.argv[1]) as f:
    schema = json.load(f)

with open(sys.argv[2]) as f:
    document = json.load(f)

validator = jsonschema.Draft7Validator(schema)


error = False
for error in validator.iter_errors(document):
    error = True
    print(error.message)

if not error:
    print("No errors found.")

