#! /usr/bin/env python

# Copyright (C) 2018- The University of Notre Dame
# This software is distributed under the GNU General Public License.
# See the file COPYING for details.

import sys
import os
import subprocess
import json
import shlex
import uuid
import platform
import threading
import threading

def write_stdout(lefile, proc, mid, lelock):
    with proc.stdout:
        for line in iter(proc.stdout.readline,b''):
            lelock.acquire()
            try:
                logfile.write('[runos-%d]out: %s\n'%(mid,line))
            finally:
                lelock.release()

def write_stderr(lefile, proc, mid, lelock):
    with proc.stderr:
        for line in iter(proc.stderr.readline,b''):
            lelock.acquire()
            try:
                logfile.write('[runos-%d]err: %s\n'%(mid,line))
            finally:
                lelock.release()



def clean_and_remove(path):
    allthings = os.listdir(path)
    for x in allthings:
        if os.path.isdir(x):
            clean_and_remove(x)
            os.rmdir(x)
        else:
            os.remove(x)
    return 1

def arr_to_str(arr):
    s = ""
    for x in arr:
        s += ("%s " % x)
    return s[:-1]
def convert(shlex_list):
    a = []
    for x in shlex_list:
        a.append(str(x))
    return a

if __name__ == "__main__":
    if len(sys.argv) < 3:
        sys.stderr.write("Usage: runos (rhel6|rhel7) [arguments ...]\n")
        exit(2)
    target = sys.argv[1]
    cmd = sys.argv[2:]
    output = 'runos-output.txt'
    switch=False
    if '--output=' in sys.argv[1]:
        switch=True
        target = sys.argv[2]
        cmd = sys.argv[3:]
        output = sys.argv[1][len('--output='):]

    #finding config file
    mydir = os.path.dirname(os.path.realpath(__file__))
    try:
        cfg = open(mydir+"/"+"runos.cfg","r")
    except IOError:
        sys.stderr.write("config file not found at: "+mydir+"/runos.cfg\n")
        exit(16)
    oslocs = json.loads(cfg.read())
    cfg.close()
    #getting image path
    try:
        osused = oslocs[target]
        osused=osused.replace("$CONFIG_PATH",mydir)
    except KeyError:
        sys.stderr.write("target OS not found in config file\n")
        exit(18)
    
    #ensure singularity on computer
    run_native=False
    try:
        proc = subprocess.Popen('~condor/software/config/get_system_info.sh',stdout=subprocess.PIPE,shell=True)
        (out, err) = proc.communicate()
        base = str(platform.dist())
        if not "has_singularity = true" in out: #no singularity
            if ('redhat' in base and '6' in base) and ('rhel6' == target or 'osg_el6' == target):
                run_native = True
            elif ('redhat' in base and '7' in base) and ('rhel7' == target):
                run_native = True
            else:
                sys.stderr.write("The System doesn't have Singularity Installed, and the target is unrecognized!\n")
                exit(17)
        #can assume singularity
        proc2 = subprocess.Popen('singularity exec %s python -c "import platform; print platform.dist()"'%osused,stdout=subprocess.PIPE,shell=True)
        (imgbase,err2) = proc2.communicate() 
        if   ('redhat' in base and '6' in base) and (('redhat' in imgbase or 'centos' in imgbase) and '6' in imgbase):
            run_native = True
        elif ('redhat' in base and '7' in base) and (('redhat' in imgbase or 'centos' in imgbase) and '7' in imgbase):
            run_native = True
    except Exception, e:
        print e
        exit(88)
    
    #calling process
    mid = uuid.uuid4()
    if switch:
        logfile = open(output,'a+')
    if run_native and not run_native:
        exitcode = subprocess.call(cmd)
        exit(exitcode)
    else:
        tmphome = "/tmp/runos_singularity_home-%d"%mid
        if not (os.path.isdir(tmphome)):
            os.mkdir(tmphome,0777)

        cmdwrap = "'cd /disk; %s'" % (arr_to_str(cmd))
        #newcmd  = ["exec","--bind","%s:/disk"%os.getcwd(),"--home","%s:%s"%(tmphome,tmphome),"--bind","/var:/var","--bind","/afs/crc.nd.edu/group/ccl/software:/cclsoftware",osused,"sh","-c",cmdwrap]
        newcmd  = ["exec","--bind","%s:/disk"%os.getcwd(),"--home","%s:%s"%(tmphome,tmphome),"--bind","/var:/var","--bind","/afs/:/afs",osused,"sh","-c",cmdwrap]

        if os.path.isfile("/usr/local/bin/singularity"):
            newcmd.insert(0, "/usr/local/bin/singularity")
        elif os.path.isfile("/usr/bin/singularity"):
            newcmd.insert(0, "/usr/bin/singularity")
        else:
            newcmd.insert(0, "singularity")
        #exitcode = subprocess.call(cmd)
        #proc = subprocess.Popen(' '.join(newcmd),stdout=subprocess.STDOUT,stderr=subprocess.STDOUT,shell=True)
        if switch == False:
            proc = subprocess.Popen(' '.join(newcmd),shell=True)
            proc.wait()
            exitcode = proc.returncode
            clean_and_remove(tmphome)
            #logfile.write('[runos-%d]ret: %i\n'%(mid,exitcode))
            #logfile.close()
            exit(exitcode)
        else:   
            logfile.write('[runos-%d]: %s\n'%(mid,'STARTING'))
            logfile.write('[runos-%d]cmd: %s\n'%(mid,' '.join(newcmd)))
            proc = subprocess.Popen(' '.join(newcmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE,shell=True)  
            lelock = threading.Lock()
            out_t = threading.Thread(target = write_stdout, args=(logfile, proc, mid, lelock,))
            err_t = threading.Thread(target = write_stderr, args=(logfile, proc, mid, lelock,))
            out_t.start()
            err_t.start()
            out_t.join()
            err_t.join()
            #with proc.stdout:
            #   for line in iter(proc.stdout.readline,b''):
            #       print(line)
            #       logfile.write('[runos-%d]out: %s\n'%(mid,line))
            #(out) = proc.communicate()
            proc.wait()
            exitcode = proc.returncode
            clean_and_remove(tmphome)
            #print(out)
            #print(err)
            #logfile.write('[runos-%d]out: %s\n'%(mid,out))
            #logfile.write('[runos-%d]err: %s\n'%(mid,err))
            logfile.write('[runos-%d]ret: %i\n'%(mid,exitcode))
            logfile.close()
            exit(exitcode)  

#vim: set sts=4 sw=4 ts=4 expandtab ft=python:

