#!/usr/bin/env python

import sys
import os
import imp
import errno
import re

def setup(input_filename):
	sys.path.insert(0, os.path.dirname(os.path.abspath(file_to_link)))

	try:
		f = open(file_to_link)
		f.close()
	except:
		sys.exit(1)

def find_module_names(filename):
	module_names = []
	try:
		f = open(filename)
	except IOError, e:
		if e.errno == errno.EISDIR:
			return []

	for line in f:
		m = re.match('import (.+)', line)
		if m:
			split = m.group(1).split(',')
			for s in split:
				tmp = s.split(' as ')
				if len(tmp) > 1:
					s = tmp[0]
				module_names.append(s.strip())
		m = re.match('from (.+) import', line)
		if m:
			module_names.append(m.group(1))
	f.close()
	return module_names


file_to_link = sys.argv[1]
setup(file_to_link)

modules = find_module_names(file_to_link)
for m in modules:
	m_split = m.split('.')
	if imp.is_builtin(m_split[0]):
		continue
	m_path = imp.find_module(m_split[0])[1]
	print m, m_path

