#! /usr/bin/python
import os
import sys
import subprocess
from optparse import OptionParser
from datetime import datetime
from stat import *


def main():
	#Problem: extension support incremental download
	parser = OptionParser(usage="usage: %prog dir-name", version="%prog 1.0")
	(options, args) = parser.parse_args()

	if len(args) != 1:
		parser.error("wrong number of arguments!")
	dirname = args[0]

	list_location = "/home/ec2-user/list"
	dir_listfilename = list_location + "/dir.list"
	file_listfilename = list_location + "/file.list"
	symlink_listfilename = list_location + "/symlink.list"
	chr_listfilename = list_location + "/chr.list"
	blk_listfilename = list_location + "/blk.list"
	fifo_listfilename = list_location + "/fifo.list"
	sock_listfilename = list_location + "/sock.list"
	unknown_listfilename = list_location + "/unknown.list"


	dir_listfile = open(dir_listfilename, "wb")
	file_listfile = open(file_listfilename, "wb")
	symlink_listfile = open(symlink_listfilename, "wb")
	chr_listfile = open(chr_listfilename, "wb")
	blk_listfile = open(blk_listfilename, "wb")
	fifo_listfile = open(fifo_listfilename, "wb")
	sock_listfile = open(sock_listfilename, "wb")
	unknown_listfile = open(unknown_listfilename, "wb")
	
	# traverse root directory, and list directories as dirs and files as files
	for root, dirs, files in os.walk(dirname):
		if len(files) > 0:
			for file in files:
				name = root + '/' + file
				if os.path.exists(name):
					mode = os.lstat(name).st_mode
					if S_ISDIR(mode):
						dir_listfile.write(name + "\n")		
					elif S_ISREG(mode):
						file_listfile.write(name + "\n")		
					elif S_ISLNK(mode):
						symlink_listfile.write(name + "\n")		
					elif S_ISCHR(mode):
						chr_listfile.write(name + "\n")		
					elif S_ISBLK(mode):
						blk_listfile.write(name + "\n")		
					elif S_ISFIFO(mode):
						fifo_listfile.write(name + "\n")		
					elif S_ISSOCK(mode):
						sock_listfile.write(name + "\n")		
					else:
						unknown_listfile.write(name + "\n")
			
		if len(dirs) > 0:
			for dir in dirs:
				name = root + '/' + dir
				if os.path.exists(name):
					mode = os.lstat(name).st_mode
					if S_ISDIR(mode):
						dir_listfile.write(name + "\n")		
					elif S_ISREG(mode):
						file_listfile.write(name + "\n")		
					elif S_ISLNK(mode):
						symlink_listfile.write(name + "\n")		
					elif S_ISCHR(mode):
						chr_listfile.write(name + "\n")		
					elif S_ISBLK(mode):
						blk_listfile.write(name + "\n")		
					elif S_ISFIFO(mode):
						fifo_listfile.write(name + "\n")		
					elif S_ISSOCK(mode):
						sock_listfile.write(name + "\n")		
					else:
						unknown_listfile.write(name + "\n")
	
	dir_listfile.close()
	file_listfile.close()
	symlink_listfile.close()
	chr_listfile.close()
	blk_listfile.close()
	fifo_listfile.close()
	sock_listfile.close()
	unknown_listfile.close()
	
	sys.exit(0)

if __name__ == "__main__":
	main()

#set sts=4 sw=4 ts=4 expandtab ft=python
