CCTOOLS_HOME = ../..

include ${CCTOOLS_HOME}/Makefile.config
include ${CCTOOLS_HOME}/Makefile.rules

all:

test-linker:
	@echo running linker tests
	@${CCTOOLS_HOME}/dttools/src/test_runner.sh *.sh

test: test-linker

clean:

install:
