all: plain.png composite.png duality.png

plain.png: plain.dot
	dot -Tpng plain.dot -o plain.png

composite.png: composite.dot
	dot -Tpng composite.dot -o composite.png

duality.png: duality.dot
	dot -Tpng duality.dot -o duality.png
