include ../../Makefile.config
include ../../Makefile.rules

all:

clean:

test:

install:
	install -d ${CCTOOLS_INSTALL_DIR}/doc
	install wavefront.html ${CCTOOLS_INSTALL_DIR}/doc
	for i in *.gif; do install $$i ${CCTOOLS_INSTALL_DIR}/doc; done
