#!/bin/bash

source "$(dirname "$0")"/test-common.bash

DIR="$(pwd)/scheduler-tests.workflow"

for concurrency in 0; do
#for scheduler in fifo-0 fifo-8 fifo-4 fifo-2 fifo-1; do
#for replication in push-async-0 push-async-8 push-async-4 push-async-2 push-sync-1; do
	for scheduler in fifo-0 fifo-1 fifo-2 fifo-4 fifo-8; do
		for replication in push-async-0 push-sync-1 push-async-1 push-async-2 push-async-4; do
			if [ "$replication" = 'push-sync-1' -a ! \( "$scheduler" = 'fifo-1' \) ]; then
				continue;
			fi
			testrun "$DIR" "$(pwd)/test.${concurrency}.${scheduler}.${replication}" "scheduler=${scheduler}&replication=${replication}" --job-concurrency="${concurrency}"
		done
	done
done

# vim: set noexpandtab tabstop=4:
