#!/usr/bin/env python 3

# Copyright (C) 2020- The University of Notre Dame
# This software is distributed under the GNU General Public License.
# See the file COPYING for details.

# This is a simple dataswarm test program intended to test the
# basic functionality and work out the detailed user's API.
# The objective is to process a single large dictionary file
# by running N tasks, where each task performs a grep to search
# for words beginning with a different letter.

# Note that this example is not yet correct or complete --
# it needs to evolve along with the emerging DataSwarm API.

import os
import sys
import json

from dataswarm import DataSwarm

def main():
    if len(sys.argv) < 2:
        print("USAGE: dataswarm_test <ntasks>\n")
        sys.exit(0)

    start = time()

    ds = DataSwarm()

    # Connect to server
    ds.connect('127.0.0.1', 1234)

    # Here, we are declaring tasks in WQ style.
    # Instead, we should declare and upload the shared input ile.
    # Then, declare each output file and task.

    for i in range(ntasks):
        task = {}
        task["command_line"] = "grep %c dict > output" % (chr(ord('a')+i,i)

        task["output_files"] = [
                "local_name": "output",
                "remote_name" : "output.%d" % i,
                "flags" : { "cache":False, "watch":False }
        ]

        task["input_files"] = [
                "local_name": "/usr/share/dict/words",
                "remote_name" : "dict",
                "flags" : { "cache":True, "watch":False }
        ]

        task["cores"] = 1
        task["memory"] = 1000
        task["disk"] = 1000

        tasks.append(task)

    for t in tasks:
        t = json.dumps(t)
        response = ds.submit(t)
        print(response)
        
    while not ds.empty():
        response = ds.wait(10)
        print(response)

    ds.disconnect()

    end = time()

    start = float(start)
    end = float(end)

    print("time: {}".format(end-start-1))

if __name__ == "__main__":
    main()
