#include "vine_file.h"
#include "vine_manager.h"
#include "vine_mount.h"
#include "vine_task.h"

#include <inttypes.h>
#include <stdio.h>

void vine_taskgraph_log_write_header(struct vine_manager *q)
{
	fprintf(q->graph_logfile, "# taskvine taskgraph version 2\n");
	fprintf(q->graph_logfile, "# TASK taskid \"program\" INPUTS fileid1 fileid fileid3 ... OUTPUTS fileid4 fileid5 ...\n");
	fprintf(q->graph_logfile, "# FILE fileid \"source\" size\n");
}

void vine_taskgraph_log_write_task(struct vine_manager *q, struct vine_task *t)
{
	if (!t)
		return;

	int id = t->task_id;

	char *name = strdup(t->command_line);
	char *p = strchr(name, ' ');
	if (p)
		*p = 0;

	fprintf(q->graph_logfile, "TASK T%d \"%s\" INPUTS ",id,name);

	free(name);

	struct vine_mount *m;

	LIST_ITERATE(t->input_mounts, m)
	{
		fprintf(q->graph_logfile, "%s ", m->file->cached_name);
	}

	fprintf(q->graph_logfile,"OUTPUTS ");

	LIST_ITERATE(t->output_mounts, m)
	{
		fprintf(q->graph_logfile, "%s ", m->file->cached_name);
	}

	fprintf(q->graph_logfile,"\n");
}

void vine_taskgraph_log_write_mini_task(struct vine_manager *q, struct vine_task *t, const char *task_name, const char *output_name )
{
	if (!t)
		return;

	/* XXX Mini-tasks do not have unique ID numbers, so make it up from the pointer address. */
	int id = (intptr_t)t;

	char *name = strdup(t->command_line);
	char *p = strchr(name, ' ');
	if (p)
		*p = 0;

	fprintf(q->graph_logfile, "TASK T-%d \"%s\" INPUTS ",id,task_name);

	free(name);

	struct vine_mount *m;

	LIST_ITERATE(t->input_mounts, m)
	{
		fprintf(q->graph_logfile, "%s ", m->file->cached_name);
	}

	/* A mini-task has exactly one implied output that is named by provided argument, not the data structure */
	fprintf(q->graph_logfile, "OUTPUTS %s", output_name );

	fprintf(q->graph_logfile,"\n");
}

void vine_taskgraph_log_write_file(struct vine_manager *q, struct vine_file *f)
{
	if (!f)
		return;

	fprintf(q->graph_logfile, "FILE %s \"%s\" %ld\n", f->cached_name, f->source ? f->source : "", f->size);

	/* If this file was generated by a mini-task, then describe that too. */
	vine_taskgraph_log_write_mini_task(q, f->mini_task, f->source, f->cached_name);
}

void vine_taskgraph_log_write_footer(struct vine_manager *q)
{
	fprintf(q->graph_logfile, "# end\n");
}
