#!/bin/sh
#This script can be used to create the mountlist file for executing one pacakge under Parrot.
package_path=""
mountlist=""
show_help()
{
	echo "Options:"
	echo "-p, --package-path         The path of the package."
	echo "-s, --shell-type           The type of shell used to do the experiment."
	echo "                           Supported shell types: csh, tcsh, bash, zsh."
	echo "-h, --help                 Show this help message."

	exit 1
}

while [ $# -gt 0 ]
do
	case $1 in
		-p | --package-path)
			shift
			package_path=$1
			;;
		-s | --shell-type)
			shift
			shell_type=$1
			;;
		-h | --help)
			show_help
			;;
		*)
			break
			;;
	esac
	shift
done

package_path=`readlink -f $package_path`
cd $package_path

mountlist="mountlist"
#construct mountlist
if [ -e $mountlist ]; then
	rm $mountlist
fi

echo "/ $package_path" >> $mountlist
echo "$package_path $package_path" >> $mountlist
cat $package_path/common-mountlist >> $mountlist

#import environment varibales
. $package_path/env_list

#initialize the repeat process
exec parrot_run -m $mountlist /bin/$shell_type
